version: "3"

includes:
  backend:
    taskfile: backend/config/tasks/taskfile_{{OS}}.yml
    dir: ./backend

tasks:
  dev-setup-backend:
    deps: [backend:setup-dev-env]

  deploy-backend:
    deps: [backend:deploy-service]

  generate-keys-backend:
    deps: [backend:generate-key-pair]
