version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
    networks:
      - trophy-service

  cache:
    build: redis
    restart: unless-stopped
    privileged: true
    command: sh init-redis.sh ${CACHE_PASSWORD}
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'
    networks:
      - trophy-service

  object-storage:
    image: minio/minio
    restart: unless-stopped
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"

networks:
  trophy-service:
    driver: bridge
