version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - trophy-service
    volumes:
      - postgres:/data/postgres

  cache:
    build: redis
    restart: unless-stopped
    privileged: true
    command: sh init-redis.sh ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - trophy-service
    volumes:
      - redis:/data/redis

  api:
    build:
      context: ../
      dockerfile: deploy/api/Dockerfile
    env_file:
      - ../config/env/.production.env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - trophy-service
    depends_on:
      - postgres
      - cache

volumes:
  postgres:
  redis:

networks:
  trophy-service:
    driver: bridge
