version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
    networks:
      - trophy-service

  cache:
    build: redis
    restart: unless-stopped
    privileged: true
    command: sh init-redis.sh ${CACHE_PASSWORD}
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'
    networks:
      - trophy-service

networks:
  trophy-service:
    driver: bridge
